version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./users.xml:/etc/clickhouse-server/users.xml
    restart: always
  
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MINIO_ENDPOINT=minio:9000
      - CLICKHOUSE_HOST=clickhouse
    depends_on:
      - minio
      - clickhouse
    volumes:
      - .:/app
    restart: always

volumes:
  minio_data:
    driver: local
  clickhouse_data:
    driver: local